### ISSUE TITLE
Building in Eclipse, Tomcat 9 + Java 8

### ISSUE THREAD

**Issue by luzlab** [musIndex/mouseinventory#5]
@jscoles Do you have some time to talk? I'm having a lot of difficulty getting this built in a modern environment. I was hoping you might be able to share some insights...

**Comment by jscoles** [comment]
I could definitely find some time.  By chance do you work at the mission bay campus?  My office is in mission bay, which could facilitate an in-person meeting.

**Comment by luzlab** [comment]
Hi Jonathan! Sorry I'm not in SF anymore, I made the move to Sunny San Diego. I just sent you an email so you can contact me directly.

**Comment by estellewall** [comment]
The issue was the mysql-connector-java-5.0.8.jar was missing, need it to run Mouse Inventory version 2.0
